spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/pcmarket
    username: postgres
    password: root123
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
  data:
    rest:
      base-path: "/api"
debug: true
server:
  port: 8088
